//jshint esversion:6

module.exports = [
    '',
    '<span id="Co. Offaly">Co. Uíbh Fhailí</span>',
    '<span id="Co. Louth">Co. Lú</span>',
    '<span id="Co. Wexford">Co. Loch Garman</span>',
    '<span id="Co. Limerick">Co. Luimnigh</span>',
    '<span id="Co. Dublin">Co. Átha Chliath</span>',
    '<span id="Co. Leitrim">Co. Liatroma</span>',
    '<span id="Co. Antrim">Co. Aontroma</span>',
    '<span id="Co. Donegal">Co. Dhún na nGall</span>',
    '<span id="Co. Fermanagh">Co. Fhear Manach</span>',
    '<span id="Co. Cork">Co. Chorcaí</span>',
    '<span id="Co. Wicklow">Co. Chill Mhantáin</span>',
    '<span id="Co. Roscommon">Co. Ros Comáin</span>',
    '<span id="Co. Derry">Co. Dhoire</span>',
    '<span id="Co. Sligo">Co. Shligigh</span>',
    '<span id="Co. Tipperary">Co. Thiobraid Árann</span>',
    '<span id="Co. Laois">Co. Laoise</span>',
    '<span id="Co. Waterford">Co. Phort Láirge</span>',
    '<span id="Co. Kilkenny">Co. Chill Chainnigh</span>',
    '<span id="Co. Meath">Co. Na Mí</span>',
    '<span id="Co. Kerry">Co. Chiarraí</span>',
    '<span id="Co. Longford">Co. An Longfoirt</span>',
    '<span id="Co. Mayo">Co. Mhaigh Eo</span>',
    '<span id="Co. Westmeath">Co. Na hIarmhí</span>',
    '<span id="Co. Down">Co. An Dúin</span>',
    '<span id="Co. Armagh">Co. Ard Mhacha</span>',
    '<span id="Co. Carlow">Co. Cheatharlach</span>',
    '<span id="Co. Monaghan">Co. Mhuineacháin</span>',
    '<span id="Co. Galway">Co. na Gaillimhe</span>',
    '<span id="Co. Kildare">Co. Chill Dara</span>',
    '<span id="Co. Clare">Co. An Chláir</span>',
    '<span id="Co. Cavan">Co. An Cabháin</span>',
    '<span id="Co. Tyrone">Co. Thír Eoghain</span>',
    '<span id="A land beyond the sea">Tír Thar Muir</span>',
    '<span id="For the language">Ar shon an Teanga</span>'
];
