//jshint esversion:6

module.exports = [
    'Uíḃ Ḟailí',
    'Lú',
    'Loch Garman',
    'Luimnigh',
    'Ḃaile Átha Ċliath',
    'Liatroma',
    'Aontroma',
    'Ḋún na nGall',
    'Ḟear Manaċ',
    'Ċorcaí',
    'Ċill Ṁantáin',
    'Ros Comáin',
    'Ḋoire',
    'Ṡligiġ',
    'Ṫiobraid Árann',
    'Laoise',
    'Ṗort Láirge',
    'Ċill Ċainniġ',
    'Na Mí',
    'Ċiarraí',
    'An LongFoirt',
    'Ṁaigh Eo',
    'Na hIarṁí',
    'An Dúin',
    'Ard Ṁaċa',
    'Ċeaṫarlaċ',
    'Ṁuineaċáin',
    'na Gailliṁe',
    'Ċill Dara',
    'An Ċláir',
    'An Caḃáin',
    'Ṫír Eoghain',
    'Thar lar'
];
